# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f5d5ff838c26a4c74fe5701d388f2903d5619fc1f455eff131afbe39634847599915dbc4c094a7e1fa0fd8a43efda6c65c335aa32e166bdbd3ff52673ef3d46

test:
  secret_key_base: 236be2d4c339416eacc1a9ac23336f6665bd3c6afc2ee605a853abbba41d77aba1c51d809437fee7d11df03d070376d38c7698747728ea596057d9d4f4097489

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
